services:
    canal_tp_navitia_io.api:
        class: CanalTP\NavitiaIoApiComponent\NavitiaIoApiService
        arguments:
            - %canal_tp_navitia_io_api.url%
            - %canal_tp_navitia_io_api.auth.user%
            - %canal_tp_navitia_io_api.auth.password%
